### ISSUE TITLE
Error `/pr_check` ketika user github ditemukan tetapi 0 kontribusi

### ISSUE THREAD

**Issue by reacto11mecha** [bellshade/bellshade-server#20]
Ada masalah ketika mengecek jumlah pull request dari si user yang belum pernah berkontribusi ke bellshade sama sekali. Ketika di cek di production, cloudflare akan merestart aplikasi dan akan menguras github token, kemungkinan akan ada masalah ketersediaan data dalam beberapa waktu kedepan.

Terimakasih kepada @ItsArul yang sebelumnya sudah menanyakan pertanyaan bellshade, akhirnya bug ini bisa di deteksi.

Ketika mengunjungi http://localhost:3000/pr_check/ItsArul, maka akan terjadi error ini

Di sisi penerima
```sh
$ curl localhost:3000/pr_check/ItsArul
curl: (52) Empty reply from server
```

Di sisi backend
```sh
{"level":30,"time":1642336353040,"pid":31101,"hostname":"ideapad","reqId":"req-1","req":{"method":"GET","url":"/pr_check/ItsArul","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":43472},"msg":"incoming request"}
TypeError: Property 'pull_requests' should be of type array, received 'null' instead.
    at $arr$mainpull_requests (eval at build (/home/ezra/code/node/bellshade-server/node_modules/fast-json-stringify/index.js:147:20), <anonymous>:295:13)
    at $main (eval at build (/home/ezra/code/node/bellshade-server/node_modules/fast-json-stringify/index.js:147:20), <anonymous>:195:17)
    at serialize (/home/ezra/code/node/bellshade-server/node_modules/fastify/lib/reply.js:728:12)
    at preserializeHookEnd (/home/ezra/code/node/bellshade-server/node_modules/fastify/lib/reply.js:372:15)
    at preserializeHook (/home/ezra/code/node/bellshade-server/node_modules/fastify/lib/reply.js:357:5)
    at _Reply.Reply.send (/home/ezra/code/node/bellshade-server/node_modules/fastify/lib/reply.js:189:7)
    at /home/ezra/code/node/bellshade-server/router/main/index.js:128:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
/home/ezra/code/node/bellshade-server/router/main/index.js:133
          if (error.response.status === 422) {
                             ^

TypeError: Cannot read properties of undefined (reading 'status')
    at /home/ezra/code/node/bellshade-server/router/main/index.js:133:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Kemungkinan akan diubah tipe response nya ketika si user belum pernah berkontirbusi sama sekali, kolom `pull_requests` akan di berikan array kosong untuk memperbaiki bug ini.

**Comment by reacto11mecha** [comment]
Okey sekarang aman buat ngecek PR nya, contoh nya kayak yang ini
https://api.bellshade.org/pr_check/ItsArul
